services:
  web:
    build: .
    image: shadowdfd/car-expenses:latest
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
